import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const sites = [
        {
            title: "Sudoku Combination Finder",
            description: "Find all combinations of a given killer sudoku",
            url: "sudoku.timofrionnet.ml",
            github: "https://github.com/timsun28/Sudoku-combination-finder",
        },
        {
            title: "Data Usage Calculator",
            description: "Calculate how much mobile data you SHOULD have left at any time in the month",
            url: "data.timofrionnet.ml",
            github: "https://github.com/timsun28/Data-Usage-Calculator",
        },
        {
            title: "Chess Clock",
            description: "An easy to use app to keep track of the time you have left in a chess game",
            url: "chessclock.timofrionnet.ml",
            github: "https://github.com/timsun28/Chess-Clock",
        },
        {
            title: "Nines Score Tracker",
            description: "Keep track of your score in the card game Nines",
            url: "nines.timofrionnet.ml",
            github: "https://github.com/timsun28/NextJS-Nines-App",
        },
        {
            title: "New Zealand DOC Hike Finder",
            description: "Find hikes in New Zealand's national parks with data from the DOC API",
            url: "doc.timofrionnet.ml",
            github: "https://github.com/timsun28/NextJS-DOC-App",
        },
    ];
    return (
        <>
            <Head>
                <title>Timo&apos;s apps</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col items-center h-screen m-2 mt-8 md:justify-center dark:text-white">
                <h1 className="text-4xl">Welcome!</h1>
                <p className="text-xl">You can find all my side projects!</p>
                <div className="flex flex-wrap items-center justify-center gap-8 mt-8">
                    {sites.map((site, index) => (
                        <div
                            key={index}
                            className="flex flex-col gap-2 px-4 py-8 border rounded-lg border-slate-800 dark:border-white w-96"
                        >
                            <h2 className="text-2xl font-bold">{site.title}</h2>
                            <p className="text-xl">{site.description}</p>
                            <a
                                href={`https://${site.url}`}
                                target="_blank"
                                rel="noreferrer"
                                className="text-xl underline"
                            >
                                {site.url}
                            </a>
                            <a href={site.github} target="_blank" rel="noreferrer" className="text-xl underline">
                                Github
                            </a>
                        </div>
                    ))}
                </div>
            </main>
        </>
    );
}
