import * as stylex from "@stylexjs/stylex";

/* StyleX names the semantic handles; tokens.css supplies their values. */
export const tokens = {
    paper: "var(--color-paper)",
    surface: "var(--color-surface)",
    surfaceHover: "var(--color-surface-hover)",
    ink: "var(--color-ink)",
    inkSoft: "var(--color-ink-soft)",
    rule: "var(--color-rule)",
    accent: "var(--color-accent)",
    accentDeep: "var(--color-accent-deep)",
    accentSoft: "var(--color-accent-soft)",
    graphite: "var(--color-graphite)",
    focus: "var(--color-focus)",
    display: "var(--font-display)",
    body: "var(--font-body)",
    mono: "var(--font-mono)",
    easeOut: "var(--ease-out)",
    easeInOut: "var(--ease-in-out)",
} as const;

export const styles = stylex.create({
    page: { minHeight: "100dvh", backgroundColor: tokens.paper, color: tokens.ink },
    nav: { alignItems: "center", borderBottomColor: tokens.rule, borderBottomStyle: "solid", borderBottomWidth: "1px", display: "flex", justifyContent: "space-between", marginInline: "auto", maxWidth: "96rem", paddingBlock: "var(--space-md)", paddingInline: "clamp(1rem, 4vw, 3rem)" },
    wordmark: { color: tokens.ink, fontFamily: tokens.display, fontSize: "var(--text-lg)", fontWeight: 600, letterSpacing: "-0.04em", minHeight: "2.75rem", textDecoration: "none", whiteSpace: "nowrap", ":focus-visible": { outlineColor: tokens.focus, outlineOffset: "3px", outlineStyle: "solid", outlineWidth: "2px" } },
    navLink: { alignItems: "center", borderColor: tokens.rule, borderRadius: "var(--radius-sm)", borderStyle: "solid", borderWidth: "1px", color: tokens.ink, display: "inline-flex", fontFamily: tokens.mono, fontSize: "var(--text-xs)", fontWeight: 500, letterSpacing: "0.04em", minHeight: "2.75rem", paddingInline: "var(--space-sm)", textDecoration: "none", transitionDuration: "var(--dur-short)", transitionProperty: "border-color, color", transitionTimingFunction: tokens.easeOut, whiteSpace: "nowrap", ":hover": { borderColor: tokens.accent, color: tokens.accentDeep }, ":active": { color: tokens.accentDeep }, ":focus-visible": { outlineColor: tokens.focus, outlineOffset: "3px", outlineStyle: "solid", outlineWidth: "2px" } },
    shell: { marginInline: "auto", maxWidth: "96rem", paddingBlock: "var(--space-3xl)", paddingInline: "clamp(1rem, 4vw, 3rem)" },
    hero: { display: "grid", gap: "var(--space-xl)", marginBlockEnd: "var(--space-3xl)", maxWidth: "72rem" },
    eyebrow: { color: tokens.accentDeep, fontFamily: tokens.mono, fontSize: "var(--text-xs)", fontWeight: 500, letterSpacing: "0.08em", margin: 0, textTransform: "uppercase" },
    title: { fontFamily: tokens.display, fontSize: "var(--text-display)", fontStyle: "normal", fontWeight: 600, letterSpacing: "-0.065em", lineHeight: 0.94, margin: 0, maxWidth: "12ch", minWidth: 0, overflowWrap: "anywhere" },
    heroBottom: { alignItems: "end", display: "grid", gap: "var(--space-lg)", gridTemplateColumns: "minmax(0, 1fr)", "@media (min-width: 48rem)": { gridTemplateColumns: "minmax(0, 1fr) minmax(12rem, 16rem)" } },
    lede: { color: tokens.inkSoft, fontSize: "var(--text-xl)", lineHeight: 1.4, margin: 0, maxWidth: "38rem" },
    count: { borderColor: tokens.rule, borderStyle: "solid", borderWidth: "1px", borderRadius: "var(--radius-card)", display: "grid", gap: "var(--space-2xs)", padding: "var(--space-md)" },
    countNumber: { color: tokens.accentDeep, fontFamily: tokens.display, fontSize: "clamp(3rem, 5vw + 1rem, 5rem)", fontWeight: 600, letterSpacing: "-0.07em", lineHeight: 0.85 },
    countText: { color: tokens.inkSoft, fontSize: "var(--text-sm)", margin: 0 },
    controls: { alignItems: "center", borderTopColor: tokens.rule, borderTopStyle: "solid", borderTopWidth: "1px", display: "flex", flexWrap: "wrap", gap: "var(--space-md)", justifyContent: "space-between", marginBlockEnd: "var(--space-xl)", paddingBlockStart: "var(--space-lg)" },
    controlLabel: { color: tokens.inkSoft, fontFamily: tokens.mono, fontSize: "var(--text-xs)", letterSpacing: "0.08em", margin: 0, textTransform: "uppercase" },
    filters: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "var(--space-xs)" },
    filter: { backgroundColor: "transparent", borderColor: tokens.rule, borderRadius: "var(--radius-sm)", borderStyle: "solid", borderWidth: "1px", color: tokens.inkSoft, cursor: "pointer", fontSize: "var(--text-sm)", fontWeight: 500, minHeight: "2.75rem", paddingInline: "var(--space-sm)", transitionDuration: "var(--dur-short)", transitionProperty: "border-color, color", transitionTimingFunction: tokens.easeOut, whiteSpace: "nowrap", ":hover": { borderColor: tokens.accent, color: tokens.ink }, ":active": { color: tokens.accentDeep }, ":disabled": { cursor: "not-allowed", opacity: 0.55 }, ":focus-visible": { outlineColor: tokens.focus, outlineOffset: "3px", outlineStyle: "solid", outlineWidth: "2px" } },
    filterSelected: { borderColor: tokens.accent, color: tokens.accentDeep },
    grid: { display: "grid", gap: "var(--space-md)", gridTemplateColumns: "minmax(0, 1fr)", "@media (min-width: 42rem)": { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" }, "@media (min-width: 76rem)": { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" } },
    card: { backgroundColor: tokens.paper, borderColor: tokens.rule, borderRadius: "var(--radius-card)", borderStyle: "solid", borderWidth: "1px", display: "grid", gap: "var(--space-md)", gridTemplateRows: "auto 1fr auto", minWidth: 0, padding: "var(--space-md)", transitionDuration: "var(--dur-short)", transitionProperty: "border-color, background-color", transitionTimingFunction: tokens.easeOut, ":hover": { backgroundColor: tokens.surface, borderColor: tokens.accent }, ":focus-within": { backgroundColor: tokens.surface, borderColor: tokens.accent } },
    cardTop: { alignItems: "start", display: "flex", justifyContent: "space-between" },
    projectMark: { alignItems: "center", backgroundColor: tokens.surface, borderColor: tokens.rule, borderRadius: "var(--radius-sm)", borderStyle: "solid", borderWidth: "1px", color: tokens.inkSoft, display: "inline-flex", fontFamily: tokens.mono, fontSize: "var(--text-xs)", fontWeight: 500, height: "2rem", justifyContent: "center", minWidth: "2rem" },
    category: { color: tokens.inkSoft, fontFamily: tokens.mono, fontSize: "var(--text-xs)", letterSpacing: "0.04em", paddingBlock: "var(--space-2xs)", whiteSpace: "nowrap" },
    cardBody: { display: "grid", gap: "var(--space-xs)" },
    cardTitle: { fontFamily: tokens.display, fontSize: "var(--text-xl)", fontWeight: 600, letterSpacing: "-0.045em", lineHeight: 1.05, margin: 0, minWidth: 0, overflowWrap: "anywhere" },
    cardDescription: { color: tokens.inkSoft, fontSize: "var(--text-sm)", lineHeight: 1.5, margin: 0 },
    cardFooter: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "var(--space-md)", justifyContent: "space-between" },
    visit: { alignItems: "center", backgroundColor: tokens.accent, borderColor: tokens.accent, borderRadius: "var(--radius-sm)", borderStyle: "solid", borderWidth: "1px", color: tokens.paper, display: "inline-flex", fontSize: "var(--text-sm)", fontWeight: 600, justifyContent: "center", minHeight: "2.75rem", paddingInline: "var(--space-md)", textDecoration: "none", transitionDuration: "var(--dur-short)", transitionProperty: "background-color, border-color", transitionTimingFunction: tokens.easeOut, whiteSpace: "nowrap", ":hover": { backgroundColor: tokens.accentDeep, borderColor: tokens.accentDeep }, ":active": { backgroundColor: tokens.graphite, borderColor: tokens.graphite }, ":focus-visible": { outlineColor: tokens.focus, outlineOffset: "3px", outlineStyle: "solid", outlineWidth: "2px" } },
    source: { alignItems: "center", color: tokens.inkSoft, display: "inline-flex", fontSize: "var(--text-sm)", fontWeight: 500, minHeight: "2.75rem", textDecorationColor: tokens.accent, textDecorationThickness: "1px", textUnderlineOffset: "0.2em", transitionDuration: "var(--dur-fast)", transitionProperty: "color", transitionTimingFunction: tokens.easeOut, whiteSpace: "nowrap", ":hover": { color: tokens.accentDeep }, ":active": { color: tokens.accent }, ":focus-visible": { outlineColor: tokens.focus, outlineOffset: "3px", outlineStyle: "solid", outlineWidth: "2px" } },
    footer: { alignItems: "center", borderTopColor: tokens.rule, borderTopStyle: "solid", borderTopWidth: "1px", display: "flex", flexWrap: "wrap", gap: "var(--space-sm)", justifyContent: "space-between", marginInline: "auto", maxWidth: "96rem", paddingBlock: "var(--space-lg)", paddingInline: "clamp(1rem, 4vw, 3rem)" },
    footerCopy: { color: tokens.inkSoft, fontFamily: tokens.mono, fontSize: "var(--text-xs)", letterSpacing: "0.04em", margin: 0 },
    footerLinks: { display: "flex", flexWrap: "wrap", gap: "var(--space-sm)" },
    footerLink: { color: tokens.inkSoft, fontSize: "var(--text-sm)", fontWeight: 500, minHeight: "2.75rem", textDecorationColor: tokens.accent, textDecorationThickness: "1px", textUnderlineOffset: "0.2em", whiteSpace: "nowrap", ":hover": { color: tokens.accentDeep }, ":focus-visible": { outlineColor: tokens.focus, outlineOffset: "3px", outlineStyle: "solid", outlineWidth: "2px" } },
});
